---
title: "tt_3"
author: "Bryce Murphy"
date: "April 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This

```{r import, echo = F}

library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
library(RCurl)
library(maps)
library(mapdata)
library(leaflet)
library(ggplot2)

path <- getURL("https://raw.githubusercontent.com/bryce-murphy/tidytuesday/master/global_mortality_3.csv")

mort <- read_csv(path) %>%
  clean_names() %>%
  rename_all(
      funs(
        str_replace(., "_percent", ""))) %>%
  mutate_if(is.numeric, funs(round(., 4)))

world <- map_data("world") %>%
  rename(country = region)


world_mort <- 
  mort %>%
  inner_join(world, by = "country") %>%
  gather(key = mortality_type, value = mortality_rate, -c(1:3, 36:40))

north_america <- "c"

# leaflet(data = world) %>%
#   addTiles() %>%
#   addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
#    




```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
